
# travis config

dist: trusty
language: r
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev
      - libv8-3.14-dev

r:
 - release

before_install:
  - R -e "install.packages(c('testthat','roxygen2','pkgload','jsonlite', 'jsonvalidate', 'knitr', 'rmarkdown','validate'))"
  - R -e "pkgload::load_all('./pkg'); roxygen2::roxygenize('./pkg')"
  - cd ./pkg

r_packages:
  - covr


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


