


#' Receive ESS json schema definition string.
#'
#' @note Currently only version 1.0.0 is supported.
#'
#' @param version \code{[character]} Version of reporting scheme.
#' 
#' @references 
#' M. van der Loo and O. ten Bosch. Design of a generic machine-readable
#' validation report structure. Version 1.0.0. 
#' \href{https://github.com/data-cleaning/ValidatReport}{link}.
#' 
#' @export
ess_json_schema <- function(version="1.0.0"){
  if (version == "1.0.0"){
    ess_json_schema_1.0.0
  } else {
    warning("Unknown scheme version")
    invisible(NULL)
  }
}

check_ess_json <- function(txt,version,...){
  schema <- ess_json_schema(version)
  v <- tryCatch( jsonvalidate::json_validate(txt, schema, verbose=TRUE)
        , error=function(e){
          stop("Validation against ESS json schema stopped.:\n %s",e$message)
        })
  if (!v){
    warning("This is not a valid ESS json validation report structure:\n")
    print(attr(v,"errors"))
  } 
  invisible(NULL)
}


#' Read ESS validation report structure
#'
#' @param \code{[character]} file An URL or file location
#' @param \code{[check]} logical Toggle checking against json schema.
#' @param ... options passed to \code{\link[base]{readLines}}
#' 
#' @family IO
#'
#' @return 
#' @export
read_vrs <- function(file, check=TRUE, ...){
  txt <- paste0(readLines(file,...),collapse="\n")
  parse_ess_validation_report(txt,check=check)
}

#' Parse ess json validation report.
#'
#' @param txt \code{[character]} json validation report string
#' @param check \code{[logical]} toggle check against json schema
#' @param version \code{[character]} json schema version to check against
#' 
#' @return Object of class \code{c("vrs","data.frame")} 
parse_ess_validation_report <- function(txt, check=TRUE, version="1.0.0"){
  if ( check ) check_ess_json(txt, version=version) 
  txt <- paste0(readLines("ex-18rulesvalidatfoundation_1000.json"),collapse="\n")
  a <- jsonlite::fromJSON(txt,flatten = TRUE)
  a$data.source <- gsub("c\\((.*)\\)","[\\1]",a$data.source)
  a$rule.severity <- factor(a$rule.severity, levels=c("information","warning","error"))
  a$value <- factor(a$value, levels=c("0","1","NA"),labels=c("TRUE","FALSE","NA"))
  class(a) <- c("vrs",class(a)) 
  a
}

#' Create a human-readable report
#' 
#' @param x an object to be downmarked
#' 
#' @export
as_markdown <- function(x,...){
  # generic, so we can overload for json string, 'validation' objects.
  UseMethod("as_markdown")
}

# easy line concatenation
`%+=%` <- function(lhs,rhs){
  out_var <- as.character(sys.call()[[2]])
  str <- paste0(lhs, "\n", rhs)
  assign(out_var, str,pos=parent.frame())
}

#' @rdname as_markdown
#'
as_markdown.vrs <- function(x, author=Sys.info()["user"], ...){
  md.str <- "# Validation report"
  md.str %+=% sprintf("Generated by %s, %s",author,date())
  
  md.str %+=% "\n## Overview of validation procedure\n"
  
  
  md.str %+=% "\nEvaluations:\n"
  basic_info <- 
    data.frame(
      Information = c("Nr of validations", "Nr of rules checked")
      , Value = c(nrow(x), length(unique(x$rule.expression)))
    )
  md.str %+=% paste(knitr::kable(basic_info, format="markdown"), collapse="\n")

  md.str %+=% "\nEvents by actor:\n"
  tab <- as.data.frame(table(a$event.actor))
  names(tab) <- c("actor","events")
  md.str %+=% paste(knitr::kable(tab),collapse="\n")
    
  md.str %+=% "\nSeverity changes:\n"
  tab <- table(severity = a$rule.severity, change = a$rule.change)
  md.str %+=% paste(knitr::kable(tab,format="markdown"),collapse="\n")
  
  
  
  md.str %+=% "\n## Overview of validation results\n"
  
  md.str %+=% "\nResults by severity (possibly after change):\n"
  tab <- addmargins(table(severity = x$rule.severity, result = x$value))
  md.str %+=% paste(knitr::kable(tab,format="markdown", caption="Results by severity"), collapse="\n")
  
  md.str
  
}











