#' @import rmarkdown
{}


#' Create a human-readable report (EXPERIMENTAL)
#' 
#' Alpha version for human-readable report generation. This function is
#' very likely to change significantly or dissapear in future versions of
#' this package.
#' 
#' 
#' @param x an object to be downmarked
#' @param ... Currently not used
#' 
#' @export
as_markdown <- function(x,...){
  # generic, so we can overload for json string, 'validation' objects.
  UseMethod("as_markdown")
}

#' @rdname as_markdown
#' @export
as_markdown.vrs <- function(x,...){
  md.str <- ""
  for (i in seq_len(nrow(x))){
    md.str %+=% md_rec(x[i,])
  }
  md.str
}

# easy line concatenation
`%+=%` <- function(lhs,rhs){
  out_var <- as.character(sys.call()[[2]])
  str <- paste0(lhs, "\n", rhs)
  assign(out_var, str,pos=parent.frame())
}

md_rec <- function(x){
  md.str <- sprintf("\n- Event id       : %s",x[["id"]] )
  md.str %+=% sprintf("      - type     : %s",x[["type"]])
  md.str %+=% sprintf("      - actor    : %s",x[["event.actor"]])
  md.str %+=% sprintf("      - agent    : %s",x[["event.agent"]])
  md.str %+=% sprintf("      - trigger  : %s",x[["event.trigger"]])
  md.str %+=% sprintf("- Value          : %s",x[["value"]])
  md.str %+=% sprintf("- Source data    : %s",x[["data.source"]])
  md.str %+=% sprintf("- Target data    : %s",x[["data.target"]])
  md.str %+=% sprintf("- Data description:\n\n```\n%s\n\n```"
          , paste("  ",strwrap(x[["data.description"]],width=60),collapse="\n"))
  md.str %+=% sprintf("- Rule          :")
  md.str %+=% sprintf("    - language  : %s",x[["rule.language"]])
  md.str %+=% sprintf("    - severity  : %s",x[["rule.severity"]])
  md.str %+=% sprintf("    - change    : %s",x[["rule.change"]])
  md.str %+=% sprintf("- Rule description:\n\n```\n%s\n```"
            , gsub("`","",paste("  ", strwrap(x[["rule.description"]],width=60),collapse="\n")))
  md.str %+=% sprintf("- Rule expression:\n\n```\n%s\n```\n\n"
   , gsub("\\n","\n  ", paste("  ",x[["rule.expression"]])))
  md.str %+=% paste(rep("-",80),collapse="")
  md.str
}



#' Create a human-readable summary
#' 
#' @param x an object to be downmarked
#' @param ... Currently unused.
#' @export
md_summary <- function(x,...){
  UseMethod("md_summary")
}



#' @rdname as_markdown
#' @param author \code{[character]} author
md_summary.vrs <- function(x, author=Sys.info()["user"], ...){
  md.str <- "# Validation report summary"
  md.str %+=% sprintf("Generated by %s, %s",author,date())
  
  md.str %+=% "\n## Overview of validation procedure\n"
  
  
  md.str %+=% "\nEvaluations:\n"
  basic_info <- 
    data.frame(
      Information = c("Nr of validations", "Nr of rules checked")
      , Value = c(nrow(x), length(unique(x$rule.expression)))
    )
  md.str %+=% paste(knitr::kable(basic_info, format="markdown"), collapse="\n")

  md.str %+=% "\nEvents by actor:\n"
  tab <- as.data.frame(table(x$event.actor))
  names(tab) <- c("actor","events")
  md.str %+=% paste(knitr::kable(tab),collapse="\n")
    
  md.str %+=% "\nSeverity changes:\n"
  tab <- table(severity = x$rule.severity, change = x$rule.change)
  md.str %+=% paste(knitr::kable(tab,format="markdown"),collapse="\n")
  
  
  
  md.str %+=% "\n## Overview of validation results\n"
  
  md.str %+=% "\nResults by severity (possibly after change):\n"
  tab <- stats::addmargins(table(severity = x$rule.severity, result = x$value))
  md.str %+=% paste(knitr::kable(tab,format="markdown", caption="Results by severity"), collapse="\n")

  md.str %+=% "\n## Results by rule:\n"
  i <- 0
  for ( rl in unique(x$rule.expression)){
    i = i + 1
    y <- x[x$rule.expression == rl,]
    md.str %+=% "------------------------------------------------------------\n"
    md.str %+=% sprintf("\n**Rule %03d: Description:**\n",i)
    md.str %+=% y$rule.description[1]
    md.str %+=% "\n**Expression:**\n"
    md.str %+=% "\n```"
    md.str %+=% rl
    md.str %+=% "```\n"
    md.str %+=% "\n\n**Results:**\n\n"
    tab <- as.data.frame(t(as.matrix(stats::addmargins(table(value = y$value)))))
    md.str %+=% paste(knitr::kable(tab, format="markdown"),collapse="\n")
  }
  
    
  md.str
  
}

